# Setup
title: KB애자일 하자CON
tagline: 우리도 애자일에 진심입니다.
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: KB국민은행 아키텍처부(P) 애자일빌드팀
  url: https://www.kbstar.com/
  email: kichang.hong@kbfg.com

# Custom vars
version: 3.0.0
